services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: pg-vector-medicoaqui
    restart: unless-stopped
    environment:
      POSTGRES_USER: telegram_bot
      POSTGRES_PASSWORD: telegram_bot_password
      POSTGRES_DB: telegram_bot
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d medicoaqui"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  prisma-migrate:
    image: telegram-gemini-bot-telegram-bot-app:latest
    depends_on:
      postgres:
        condition: service_healthy 
    env_file:
      - .env
    command: npx prisma migrate deploy
    restart: "no" 

  telegram-bot-app:
    build: 
      context: .
    container_name: telegram-bot-app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      prisma-migrate:
        condition: service_completed_successfully

  adminer:
    image: adminer
    container_name: adminer-medicoaqui
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pg_data:
    driver: local
